/*
  # Add Parent Testimonials for Baby English Program
  
  1. Insert 20+ detailed parent testimonials
  2. All testimonials linked to "bebeğimle-evde-ingilizce" program
  3. All testimonials have 5-star rating
  4. Testimonials in Turkish with detailed feedback
*/

-- Insert parent testimonials for Baby English Program
INSERT INTO parent_testimonials (parent_name, student_info, testimonial_text, rating, program_slug, is_featured, is_active, display_order) VALUES
  ('Gonca & Tolga Ç.', 'İkizlerimiz', 'Gonca Hocam size çok güzel haberlerim var. Biliyorsunuz ben sizi ikizlerim doğmadan takip ediyordum. Sonrasında 0-2 yaş ingilizce eğitiminize katılmıştık. Sürekli annesi ve babası olarak ingilizce konuşuyorduk ve eğitimdeki tüm konuları titizlikle işledik. Konuyla ilgili tüm müzikleri speaker''dan dinlettik. İngilizce uyku müziklerini ve önerdiğiniz çizgi filmleri dinlettik ve hala da dinletiyoruz. Dün İngilizce olarak "where''s the doctor?" diye sorduk halı üzerinde gidip doktoru gösterdi. Ayağa kalk diyoruz kalkıyor. Gözlüğümü çıkarır mısın diyorum çıkartıyor. Geri dönüşümler geldikçe geliyor ve çok mutlu olduk eşimle. Size çok teşekkür etmek istedim ve paylaşmak istedim. İyi ki varsınız Gonca Hocam.', 5, 'bebeğimle-evde-ingilizce', true, true, 100),
  
  ('Nesrin Ö.', 'İngilizce öğretmeni, 2. çocuğum 1 yaşında', 'Ben de bir İngilizce öğretmeniyim. 1.çocuğumu çift dilli yetiştirememek içimde bir yaraydı. 2.çocuğum 1 yaşındayken Gonca hanımın programını gördüm. Biraz cesaretimi toplayıp motive olmak istediğim için bu programa katıldım. İyi ki de katılmışım diyorum şu anda. Bir 0-2 yaş aralığında bebekle kurulabilecek bütün diyaloglar, şarkılar vs.vs. birçok gerekli olan kaynak doyurucu bir şekilde bize verildi. 12 haftalık günlük hayattan bebeğimizle konuşulabilecek konularla hazırlanmış güzel bir programdı. Bu 3 aylık süreçte her gün motive olarak ingilizce konuştum ve bebeğimin söylediklerimi anladığını gördüm konuşamasada karşılık verdi. Gonca hanımın samimi içten yaklaşımı her sorumuza ayrıntılı bir şekilde cevap vermesi ve gerçekten yardımcı faydalı olmaya çalışması nedeniyle kendisine teşekkürü bir borç bilirim. Bundan sonraki süreçte bebeğimi çift dilli yetiştirmek adına bana ilham kaynağı olduğu için de ayrıca çok teşekkür ederim.', 5, 'bebeğimle-evde-ingilizce', true, true, 101),
  
  ('Meryem Y.', 'Çocuğum', 'Her şey için çok teşekkür ederiz. Programa iyi ki katılmışım diyorum belli seviyede İngilizcemiz olsa da ne diyeceğimiz nasıl telaffuz edeceğimiz noktasında yetersiz kalıyorduk. Program bize çok fazla cümle örneği sunmuş oldu, aynı şekilde şarkılar tekerlemelerle pekiştirme yapmamızı sağlamış oldu. Çok teşekkür ederiz, emeğinize sağlık.', 5, 'bebeğimle-evde-ingilizce', true, true, 102),
  
  ('Yaren A.', 'Kızım 15 aylık', 'Merhaba Gonca hocam verdiğiniz program çok faydalı, çok yararlı. Kızıma tek başıma yabancı dil öğretmek istesem kelime öğretimi dışına çıkamazdım. Çok teşekkür ederim değerli paylaşımlarınız için. Bu arada kızım 15 aylık program esnasında okey, fork, no no no, happy dedi ve "where is the yellow ball?" sorusuna da yok diye cevap verdi.', 5, 'bebeğimle-evde-ingilizce', true, true, 103),
  
  ('Canan E.', 'Bebeğim 4 aylık', 'Çok teşekkür ederim. Gerçekten işinizi o kadar güzel yapıyorsunuz ki. Ben de bu süreçte oldukça gelişim sağladım. Bebeğim henüz 4 aylık ama anladığına eminim. İlk dönüşleri alınca sizinle paylaşacağım.', 5, 'bebeğimle-evde-ingilizce', false, true, 104),
  
  ('Adile Z.', 'Çocuğum', 'Çok güzel ve verimli bir programdı. Dili bilmeme rağmen bu yaş grubuna nasıl faydalı olacağımı bulamamıştım. Çok ışık oldunuz bana emeğinize sağlık. Yavaş yavaş emin adımlarla ilerliyoruz. Çok teşekkürler.', 5, 'bebeğimle-evde-ingilizce', false, true, 105),
  
  ('Zeliha Kayhan', 'Çocuğum', 'Gonca hocam ile yaptığı ilk "Çocuğumla Evde İngilizce" platformunda tanıştım. Daha önceden de severek takip ediyordum ama böyle bir ortamda tanışmak da nasip oldu. Yaptığı çalışmalarla her hafta bize çocuklarımızla farklı konularda aktiviteler yapma ve bir de bunları İngilizce olarak yaparak bir taşla iki kuş vurma fırsatı sağladığı için kendisine buradan kocaman teşekkür ediyorum. Gönderdiği her dosya ayrı bir emek ve birikimdi. Bizimle paylaşması çok kıymetli. Ayrıca her hafta bu konuyla ilgilenen anne ve babalara bir araya gelmek ve deneyimlerimizi paylaşmak harikaydı. Gonca hocam''ın da bu görüşmelerde bizi dinleyip yol göstermesi tabiri caizse gaz vererek motivasyonumuzu arttırması çok güzeldi. Her görüşmede gözlerinin içi gülerek bizi karşılaması, sıkmadan tane tane konuşması ve en önemlisi her sıkıştığınızda tüm mesajlarınıza sabırla dönmesi bana resmen mütevazilik neymiş öğretti. Yaşadığımız sıkıntıları zamanında yaşamış ve alanında uzman bir anneyle bu yolculuğa çıkmak isteyen herkes gözü kapalı Gonca hocam''ın atölyelerine katılmalı. Ben faydasını gördüm, herkes de faydalansın isterim. Türkiye''de ilk kez kendisinin hazırladığı bu platforma katılmak harika bir deneyimdi ve katkısı tartışılmaz. Buradan yine yeniden kendisine sabrı ve emekleri için çok teşekkür ediyorum. Kararsız kalan herkese buradan faydalı olmak dileğiyle... Hoşçakalın', 5, 'bebeğimle-evde-ingilizce', true, true, 106),
  
  ('Canan Korhan', 'Çocuğum', 'Ebeveynlere çok güzel model ve örnek oluyorsunuz, çok iyi bir rehbersiniz. Çok sağolun herşey için.', 5, 'bebeğimle-evde-ingilizce', false, true, 107),
  
  ('Güler Kuşçu', 'Çocuğum', 'Çocuğumla programa başlamadan önce de İngilizce konuşuyordum ama süreyi arttırmam gerektiğini anladım. Programla birlikte benim de günlük İngilizcem gelişti, kelime haznem zenginleşti. Sizi her hafta görmek konuşmama da motivasyon oldu. Katkılarınız çok değerli.', 5, 'bebeğimle-evde-ingilizce', false, true, 108),
  
  ('Esra Savaş', 'İki buçuk yaşında ikizlerim', 'Sizinle birlikte başladığımız bu yolda çok güzel aşamalar kaydettik ve açıkçası ben çok memnunum. İki buçuk yaşında İkizlerim var benim ve dile kolay bazen Türkçe bile iletişim kurmakta çok zorlanıyorken İngilizce nasıl olur diye düşünüyordum. Sizden önce ufak ufak denemelerim oluyordu ama eğlenceli bir disiplin oluşturamamıştım. Birde farkettim ki günlük diyaloglarda oldukça zorlanıyorum ve bu hiç iş İngilizcesine benzemiyor :) Bu eğitimin en büyük katkısı oldukça basit olan günlük diyaloglarda hem kendimi geliştiriyorum hem de çocuklarıma öğretiyorum. Aslında gözümde büyüttüğüm kadar zor bir olay değilmiş. Sabırlı olmak ve emek vermek gerekiyor. Aslında 3 aylık bir program olarak görmüyorum ben bunu, çok uzun süre faydalanacağım bilgiler ve kaynaklar aldım sizden, en önemlisi de cesaret verdiniz. Emeğinize sağlık hocam, Sevgiler', 5, 'bebeğimle-evde-ingilizce', true, true, 109),
  
  ('Ayşe Kamacı', 'Çocuğum', '3 aylık süreçte Gonca hanım her daim yanımızda oldu, aklımıza takılan her şeyi rahatça sorabildik, kendisi de detaylıca cevap verdi. Gayet kibar ve saygılı bir insan. Her hafta paylaşılan dökümanlar çok faydalı oldu. Haftalık görüşmelerde hiç sıkılmadım mesela bu benim için çok önemli bir unsur. Özetle, çocuğunu çift dilli yetiştirmek isteyen aileler için Gonca hanımın bu 3aylık eğitimini tavsiye ederim. Genel hatlarıyla insana nasıl bir yol izlemesi gerektiğini çok güzel öğretiyor. Ben çok memnun kaldım.', 5, 'bebeğimle-evde-ingilizce', false, true, 110),
  
  ('Fulya Seyhan', 'Bebeğim 7 aylık, İngilizce öğretmeniyim', 'Bebeğimle ingilizce programına başlama nedenim 7 aylık bebeğime ingilizce öğretmeye nereden başlayacağımı bilemememdi. Kendim de ingilizce öğretmeniyim ama sınıfta ingilizce öğretmeye benzemiyor bebeğine ingilizce öğretmek.. Hem çok kolay, hem çok zor.. Zaten hakim olduğunuz bir dili öğreteceğiniz için kolay, öğretme yöntemlerini ve karşılaşacağınız zorluklarla başetme yollarını bilmediğiniz için zor.. Gonca öğretmenimin bu eğitimiyle acabalarım, nasıllarım cevaba kavuştu.. Çok teşekkür ediyorum size öğretmenim.', 5, 'bebeğimle-evde-ingilizce', true, true, 111),
  
  ('Efnan Özkan', 'Oğlum 10 aylık, okul öncesi eğitimcisiyim', 'Bir okul öncesi eğitimcisi olarak bebeğime dil öğretmek değil, dil edindirmek istedim. İnglizce konusunda bir sıkıntım yoktu, programa katılma amacım bunu doğru yöntemle yapabilmekti. Şuan iyi ki kaçırmadan katılmışım diyorum çünkü İngilizce''nin yanısıra diğer dil olan Rusça''da da sizin rehberliğinizle herşey çok kolaylaştı. Üç dil arasındaki dengeyi kurduk, tek bir kelime dahi öğretmek gibi bir çabam yok çünkü üç dille de inanılmaz rahat yaşar hale geldik. Oğlum tam 10 aylık, ışıkları aç kapat, otur kalk, dokunma, orada dur gibi temel komutların yanı sıra köpek, elma, muz nerede, su ister misin gibi sorulara da beden diliyle karşılık veriyor. Bunları hem İngilizce de hem de diğer iki dilde yapabiliyor olmasını sizin rehberliğinize borçluyum. Beklentimin üstünde bir program oldu, ki henüz aktivite kısımlarını uygulamaya başlamadım bile. Çocuk İngilizcesine de daha hakim hale geldim. Çokça teşekkürlerimi kabul edin lütfen.', 5, 'bebeğimle-evde-ingilizce', true, true, 112),
  
  ('Zehra Öztürk', 'Kızım 9,5 aylıktan 12 aylığa', 'Merhaba Gonca hanım. Program çok faydalı oldu gerçekten. Çift dillilik konusunda daha önce kitaplar okumama rağmen kendime güvenim yoktu, soru işaretlerim de çoktu. Sizin somut etkinlik önerileri sunmanız, deneyimleriniz, diğer katılımcılarla beraber bu yola başlamak, gerektiğinde başvurabileceğim bir rehber ile içim daha rahat ilerliyorum bebeğimle. Programa başladığımızda kızım 9,5 aylıktı. Şimdi 12 aylık. Where... ile başlayan belli sorularda hemen dikkat kesilip aramaya geçiyor. Parmak oyunlarına ve şarkılara ilgi gösteriyor. Henüz İngilizcede "woof woof"u taklit etmek dışında bir üretimi yok ama anladığını görüyorum. Haftanın dosyalarında yer alan günlük dilden, en çok da aktivite/kitap/şarkı önerileri konusunda yararlandım.', 5, 'bebeğimle-evde-ingilizce', false, true, 113),
  
  ('Neslihan Poyraz', 'Bebeğim 10 aylık', 'Ben örneklerinizden ve haftalık konulardan çok memnunum, ilk başladığımızda bunları nasıl yetiştireceğim kaygısından kurtuldum ve gün içerisinde konuştukça dakikalari arttırdım. Bazı günlerde hiç konuşamıyoruz ama daha 10 aylık olduğu için çok çok takmamaya çalışıyorum ilerisi için çok uzun yolumuz var sonuçta. Yavaş yavaş yapmaya çalışıyorum ve sizin anlatım yönteminizden çok memnunum.', 5, 'bebeğimle-evde-ingilizce', false, true, 114),
  
  ('Ebru D.', 'Perla 18 aylık', 'Program yönlendirmeleri ve içerikler çok güzeldi. Biz ingilizce bilen aile olarak çocuğumuza nasıl aktarım yapacağımızı bilmiyor bocalıyorduk. Bence en en faydalı kısmı bu oldu. Doğru yöntemi öğrenmiş olduk. Perla (18 Aylık) artık anlıyor diyebilirim basic cümleleri. Göstererek ya da kelimeleri söyleyerek cevaplar veriyor. Bakışlarından da anladığı anlaşılıyor. özellikle şarkılarla çok daha hızlı kapıyor kelimeleri. Çok keyifliydi, çok teşekkür ederim emekleriniz için.', 5, 'bebeğimle-evde-ingilizce', false, true, 115),
  
  ('Gürbüz A.', 'Çocuğum, ikinci oğlum yolda', 'Programın ebeveynler için olması ayrıca harika zira öğrenmeden öğretmek mümkün olmuyor. Çocuğum bu dönemde daha da İngilizceye odaklanır oldu çünkü sayenizde ona verebilecek doneler elde ettim. Çocuklar gerçekten inanılmaz. Yıllardır sizi takip ediyorum ve iyi ki bize dokundunuz, iyi ki sizinle karşılaştım ve iyi ki varsınız Hocam. Her şey için teşekkür ederim. Haftaya Çarşamba yeni çift dillik süreci başlayacak çünkü ikinci oğlum doğacak :)', 5, 'bebeğimle-evde-ingilizce', false, true, 116),
  
  ('Buket D.', 'Oğlum', 'Çok güzel bir süreçti, planlı kaynakları bol, yönlendirmeleri bol hafta hafta çalışıp çocuğuma aktarmaya çalışarak keyifle geçti, ilerleyemeyip motivasyonumun düştüğü noktalarda destek verici yönlendirmeleriniz için ayrı teşekkür ederim, sayenizde çok güzel bir ingilizce kitap bölümümüz oldu ayrıca, şuan oğlumla ufak tefek karşılıklı ingilizce sohbet edebiliyoruz herşey için çok teşekkür ederim iyiki katıldım dediğim bir kurs kendimi çok şanslı hissediyorum elinize emeğinize sağlık.', 5, 'bebeğimle-evde-ingilizce', false, true, 117),
  
  ('Sinem Ö.', 'Çocuğum', 'Çok iyi düşünülmüş, dolu dolu işlenmiş, her anlamda yol gösterici, ciddi emek verilmiş içerikler sundunuz bize. Sadece bugün için değil, ilerde kullanabileceğimiz şeyler bile var. Size olan güvenimizin altını fazlasıyla doldurdunuz, bence Türkiye''de bir ilk olarak bu başarınızla gurur duymalısınız. Çocuklarınız çok şanslılar, umarım bizler de çocuklarımıza bir şeyler katabiliriz ve bir gün size ektiğiniz bu tohumların filizlendiğini göreceğiniz geri dönüşler verebiliriz, çok teşekkürler her şey için.', 5, 'bebeğimle-evde-ingilizce', false, true, 118),
  
  ('Nurten O.', 'Çocuğum', 'Hocam sizi tanımak çok güzeldi. Harika bir program oldu. Emekleriniz için çok teşekkürler.', 5, 'bebeğimle-evde-ingilizce', false, true, 119),
  
  ('Özlem A.', 'Çocuğum', 'Hocam çok sağolun her şey için, başlarken ki durumumla şimdiki arasında inanılmaz fark var. Neyi nasıl yapmalıyız her şey çok güzel işlendi. Emeğinize sağlık. Her şey için tekrar teşekkürler, tatlı enerjinizle hastayken bile hep motiveydiniz, çok çok sağ olun kattıklarınız için.', 5, 'bebeğimle-evde-ingilizce', false, true, 120),
  
  ('Eda H.', 'Çocuğum', 'Herşey için teşekkürler hocam. Sizi tanımak ve bu programda yer almak çok güzeldi.', 5, 'bebeğimle-evde-ingilizce', false, true, 121);
