/*
  # Add 20 Parent Testimonials for Kids Online English Program
  
  1. Insert 20 detailed parent testimonials
  2. All testimonials linked to "cocuklar-icin-online-ingilizce" program
  3. All testimonials have 5-star rating
  4. Testimonials in Turkish with detailed feedback
  5. Display order: 200-219 (new program series)
*/

-- Insert 20 parent testimonials for Kids Online English Program
INSERT INTO parent_testimonials (parent_name, student_info, testimonial_text, rating, program_slug, is_featured, is_active, display_order) VALUES
  ('Sevgi B.', 'Demir Emre - 5. Sınıf', 'Gonca hanım merhaba, Demir Emre sizle 3 defa ders alma şansı bulmuştu. Biz bu süre de çok zevk aldık. Çok memnun kaldık. Yazın devam etmek istedik fakat taşınma işlerimiz vardı. Biraz zorlu ve uzun bi süreçti bizim için. Size bir teşekkür etme fırsatı bile bulamadım. Demir şu an da 5. Sınıf ve taşındığımız yerde gittiği okulda haftalık 14 saat İngilizce dersi görüyor. Şimdiden yeni başlamasına rağmen derslere sizinle geçirdiği derslerin faydasını gördük. En büyük artısı hep ingilizce konuşarak anlatmanız, bu yüzden anlaması daha iyi seviye de. Bütün emekleriniz için teşekkür ederiz. Tekrar yolumuzun kesişmesi dileğiyle hoşçakalın.', 5, 'cocuklar-icin-online-ingilizce', true, true, 200),
  
  ('Özge S.', 'Oğlum', 'Gonca Hanım her şey için çok teşekkür ederiz. Oğlum inanılmaz bir özgüvenle başladı okula. İlginiz, sevecenliğiniz, nezaketiniz sayesinde oğlumun hem öğretmen hem İngilizce konularındaki algısı tamamen değişti. Diğer kurlarda yine buluşmak dileğiyle, hoşçakalın.', 5, 'cocuklar-icin-online-ingilizce', true, true, 201),
  
  ('Gizem Ç.', 'Çocuğum', 'Bizim için öncelikle önemli olan dersi sevip kabullendirmekti ilk adım ve sizin sayenizde o ilk eşiği çok severek geçtik. Her dersi heyecanla bekledi ve ilgi odağı olmaya başladı. Gün içinde objelerin İngilizcesini merak etti düşünmeye başladı bu neydi şu neydi diye. Dersleriniz gerçekten öğrenciyi konuşturma odaklı ve çok eğlenceliydi. Hiç bilmeyen bir öğrenciyi bile sıkmadan eğlenceli aktivitelerle basit cümlelerle dili kullanmalarını sağladınız. Bu gerçekten çok teşvik edici. Sisteminizi çok sevdim ve gayet başarılı bence.', 5, 'cocuklar-icin-online-ingilizce', true, true, 202),
  
  ('Bircan Y.', 'Defne', 'Gonca hanım merhaba. Sizin sayenizde bütün yazımızı hem eğlenerek hem de öğrenerek geçirdik. Bu süreçte Defne cümle kurma ve konuşma konusunda kendini baya geliştirdi, farkında olmadan sorulan sorulara ve nesneleri ingilizce cevaplayarak bizi mutlu etti. Günlük hayatta daha çok ingilizce kelimeleri telaffuz ediyor. Herşey için çok teşekkürler tekrar görüşmek dileğiyle. Sevgiler.', 5, 'cocuklar-icin-online-ingilizce', false, true, 203),
  
  ('Senem A.', 'Çocuğum', 'Her şeyden önce nezaketiniz, yumuşacık ses tonuyla yaklaşımınız ve ne zaman görüşmek istesek, aklımıza takılanları sabırla ve sevgiyle cevaplamak için telefonun hep diğer ucunda olduğunuz için çok çok teşekkür ediyorum. İlk derslerimizi hatırlıyorum ağlamıştı anlamadığı için ama Gonca Hanım sadece "olacak acele etmeyin ben halledicem" demişti ve öyle de oldu. Ders günlerini severek bekliyor artık. Emekleriniz için çok teşekkür ediyorum iyi ki yollarımız kesişti. Yazmadan geçemeyeceğim dersin sonlarında yaptığınız konuşmaları anlaması, merak ettiği bir şeyi sorması ve aldığı cevabı doğru şekilde anlaması mutluluk verici.', 5, 'cocuklar-icin-online-ingilizce', true, true, 204),
  
  ('Fatma G.', 'Kızım', 'Gonca Hanımla ev konforunda İngilizce programı kızımın dilini açtı ve hatta bu eğitici ve eğlenceli programla yeni bir dil öğrenmenin keyfine varınca kızım Japonca ve Yunanca da öğrenmek istediğini söyledi. İngilizceyi geliştirirken bir yandan da yeni dil öğrenimine özendirdiği için Gonca Hanıma minnettarız.', 5, 'cocuklar-icin-online-ingilizce', false, true, 205),
  
  ('Evrim A.', 'Oğlum', 'Online İngilizce dersi nasıl olur, masa başında oturmakta zorlanır mı derken oğlumun İngilizce öğrenme serüveninde bu kadar hevesli ve mutlu olduğunu görmek beni inanılmaz sevindiriyor. Derslerdeki enerjiniz, sabrınız ve ona olan yaklaşımınız sayesinde İngilizceye olan ilgisi her geçen gün artıyor. Her ders sonrası yeni bir şey öğrenmiş olmanın mutluluğuyla çıkıyor. Emeğiniz ve bu güzel katkılarınız için size çok teşekkür ederiz! İyi ki varsınız!', 5, 'cocuklar-icin-online-ingilizce', true, true, 206),
  
  ('Handan G.', 'Oğlum', '3 seviyedir ara vermeden devam ediyoruz ve son kurda ciddi bir ivme katettiler, uzun cümleler kurmaya başladı oğlum, biz kesinlikle çok memnunuz. Aralıktaki grupla devam etmeyi de düşünüyoruz.', 5, 'cocuklar-icin-online-ingilizce', false, true, 207),
  
  ('Gülden S.', 'Oğlum - Almanca eğitim veren okul', 'Oğlum derslere severek katılıyor. Almanca eğitim veren bir okulda biliyorsunuz, Almancayı sevdiği kadar İngilizceyi de seviyor artık. Kısa yurt dışı seyahatimizde her konuda konuşmak için atıldı, sayenizde özgüveni iyice arttı, çok mutlu olduk. Severek devam ediyoruz, devam edeceğiz, iyi ki sizinle yollarımız kesişmiş. Havaalanında da eşim Tax free halletmeye gitmişti biz eşyalarla beklerken, ben de gideyim babamın İngilizcesi benim kadar iyi değil deyip babasının yanına gitti.', 5, 'cocuklar-icin-online-ingilizce', true, true, 208),
  
  ('Duygu C.', 'Defne', 'Merhaba hocam, Online eğitime başlamadan önce sizi uzun süre takip ettim eğitime başlarken Defne ye faydalı olacağını biliyordum ama inan bu kadarını ben de beklemiyordum birincisi derslere katılırken çok istekliydi hatta son ders sonrası çok üzüldü derslerin bittiğine neyse ki sizinle devam ediyoruz çabuk atlattı. ikincisi Online olmasına rağmen bu kadar verimli ve etkili olacağını beklemiyorduk telaffuz kelime dağarcığı ve kalıpları uygun yerlerde günlük hayatta kullanması uyguladığınız öğretim şeklinin ne kadar etkili olduğunu gösterdi. Teşekkür ediyoruz iyi ki varsınız. Eylül de görülmek dileğiyle.', 5, 'cocuklar-icin-online-ingilizce', true, true, 209),
  
  ('Pınar K.', 'Kızım', 'Gonca öğretmenim her çocuğun sizin gibi bir İngilizce öğretmeni olmalı, gerçekten harika bir eğitmensiniz❤️Özellikle de hata yaptıklarında onlarla birlikte doğru konuşmalarını sağlamanız ve hemen ardından da o güzel ses tonunuzla "well-done" "great job" diye seslenmeniz;) Kızımın suratındaki o güzel ifadeyi kelimeler ile ifade etmek gerçekten zor;) Kızıma tekrar İngilizceyi sevdirdiniz, konuşurken hata yapacağım korkusunu aşamayan bir çocuk yerine kendinden emin coşkuyla konuşabilen biri geldi. Gonca öğretmenimiz tüm destekleriniz için sonsuz teşekkür ederiz.', 5, 'cocuklar-icin-online-ingilizce', true, true, 210),
  
  ('Sevda A.', 'Çocuğum', 'Acaba uzaktan eğitimle İngilizce dersi olur mu diyerek başladığımız kurun iki etabını bitirip üçüncüye başlamak için gün sayıyoruz. Gonca öğretmen uzaktan eğitim İngilizce dersleri için biçilmis bir kaftan, samimiyeti, profesyonelliği, çocuklara ilettiği enerjisi anlatılmaz, yaşanır. İyi ki..', 5, 'cocuklar-icin-online-ingilizce', false, true, 211),
  
  ('Hürrem K.', 'Mete', 'Öncelikle full ingilizceyle geçen 50 dakikalık bu eğitim süreci, haftada 2 gün oluşu, derslerin tatlı bir ingilizce şarkıyla bitişi, derslerde anlamadıkları zaman tekrar vurgularınızla odak noktaya çocugu çekmeye çalışmanız, öğreticiliğinizin verimi çok iyiydi. Bunlar benim çok memnun kaldığım durumlar. Metenin sizle tanışana kadar ingilizce hakkında tek bir fikri olmayışını göz önüne alırsak, çok kazanım elde ettiğini düşünüyorum. Son 2 dersi kaçırmasından beri 1 haftadır hayatında hiç ingilizce olmadığı için bugün bana "Daha güzel İngilizce konuşmak istiyorum" diye talepte bulunması ingilizceye olan farkındalığının ve sevgisinin oluştuğunu gösterir ki bu sizin başarınız. İyi ki de sizi tanıdım iyi ki de dersinize kaydettim. Sayenizde severek başladığı bir yolculuk oldu. Eğitim benim beklentimi karşıladı, sizi bırakmayı düşünmüyorum. Belki ara verebilirim ama online derslerde çevremede severek tavsiye ettiğim kıymetli bir hocamsınız. İlerde yine online düşünürsem kesinlikle bu siz olursunuz.', 5, 'cocuklar-icin-online-ingilizce', true, true, 212),
  
  ('Sinem T.', 'Haziran', 'Öncelikle, sizin derslerinize başlamadan Instagram sayfanızı takip edip, çok güzel bir enerjiniz olduğunu düşünüyordum. Haziran derslere başladığında aynı şekilde sizi çok sevdiğini söyledi.. 3 ay önce farklı bir platform üzerinden birebir ders alıyorduk. Ancak sizin derslerinize başladığımızda 5 kişilik grup halinde derse katılmayı sevdi ve daha rahat olduğunu, kendini daha rahat ifade edebildiğini söyledi. Amacım zaten topluluk içinde çekinmeden konuşmasını desteklemekti, bunu başarmaya adım attığımızı hissediyoruz, İlginiz ve emeğiniz için çok teşekkür ederiz.. Sevgiler', 5, 'cocuklar-icin-online-ingilizce', false, true, 213),
  
  ('Bahriye S.', 'Oğlum', 'Kurs başlangıcına göre oğlumun yeni kelimeler öğrendiğini ve telaffuzunda düzelmeler olduğunu gördük. Bunun dışındada İngilizce dinlemelerde 4-5 kere dinlese de anlamakta zorlanıyordu şu an 1-2 dinlemede anlayabiliyor.', 5, 'cocuklar-icin-online-ingilizce', false, true, 214),
  
  ('Zeynep O.', 'Çocuklarımız', 'Çocuklarımızın sevgili "Gonca teacher"ı her şeyden önce çocuklarla iletişimi mükemmel nadir öğretmenlerden. Dersler öyle güzel geçiyor ki zaman su gibi akıp geçiyor. Çocuklar hem eğlenip hem öğreniyorlar sayesinde. İyi ki varsınız Gonca teacher.', 5, 'cocuklar-icin-online-ingilizce', false, true, 215),
  
  ('Hale Nur Ö.', 'Oğlum', 'Gonca öğretmenim, oğlum doğduğundan beri çift dilli yetiştirmek adına araştırdığım ve bulduğum kıymetli öğretmenimiz. Çok uzun yıllar kendisini takipteyim ve yüzyüze eğitimlerde de gördüğüm üzere çok sevecen, çok sabırlı ve İngilizceyi eğlenceli olarak öğretmek adına elinden gelen her şeyi yapıyor. Sizi çok seviyoruz ❣️', 5, 'cocuklar-icin-online-ingilizce', false, true, 216),
  
  ('İlkay K.', 'Kağan', 'Öncelikle her şey için teşekkür ederiz. Online ortamda oğlum çok dinler mi ve fayda sağlar mı diye emin olamamıştım. Ancak beklentimin çok üstünde dersler faydalı oldu. Kağan İngilizceyi çok sevmeye başladı ve yabancı dil öğrenimine ilgisi arttı. Bu, okuldaki dersine de yansıdı. Kendine güveni artıp derste çekinmeden rahatlıkla İngilizce konuşabildiği öğretmenlerimiz tarafından özellikle belirtildi. Yabancı dil öğrenimi konusunda sayenizde bir kırılım yaşadığımızı düşünüyorum. Türkçe okuma yazmayı yeni öğrenen çocuklarda ikinci bir dili öğretmek ve ilgilerini çekebilmek zorken sizin sayenizde biz bunu başardık. Bu yüzden size ne kadar teşekkür etsem az. İlginiz ve emeğimiz için çok teşekkür ederiz.', 5, 'cocuklar-icin-online-ingilizce', true, true, 217),
  
  ('Tuba B.', 'Ela', 'Süreç boyunca enerjiniz ve pozitifliğiniz ekrandan çocukları aşarak evimize ulaştı. Ela her zaman bu akşam dersim var diyip koşarak odasına gitti. Onun bu kadar aktif ve mutlu şekilde derse katılım sağlaması bizlerin doğru tercih yaptığını bir kez daha kanıtlamış oldu. Dersin haricinde sorduğumuz sorulara nezaket ve ilgiyle verdiğiniz cevaplardan dolayı size teşekkür ediyorum. Emeğiniz ve desteğiniz tekrar teşekkürler, tekrar görüşmek dileğiyle...', 5, 'cocuklar-icin-online-ingilizce', false, true, 218);
